services:
  app:
    image: wave_orchestrator
    env_file:
      - .env
    ports:
      - "5050:5050"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOMAIN=${DOMAIN:-localhost:5000}
      - APPLICATION_ROOT=${APPLICATION_ROOT:-/}
      # These environment variables help Flask understand it's behind a proxy
      - FLASK_ENV=production
      - WERKZEUG_PROXY_FIX=1
      - PROXY_PREFIX=1
      - SERVER_NAME=${DOMAIN:-localhost:5050}
